### ISSUE TITLE
VBS script returns the Russian service names and descriptions in an unknown encoding

### ISSUE THREAD

**Issue by djooberlee** [PluginsOCSInventory-NG/services#3]
VBS script returns the Russian service names and descriptions in an unknown encoding
Like this:
			<SERVICE>
				<SVCNAME>Dhcp</SVCNAME>
				<SVCDN>DHCP-������</SVCDN>
				<SVCSTATE>Running</SVCSTATE>
				<SVCDESC>���������� � �������� IP-���� � DNS-����� ��� �⮣� ��������. �᫨ ������ �㦡� ��⠭������, ��� �������� �� ᬮ��� ������� �������᪨� IP-���� � �믮����� ���������� DNS. �᫨ �� �㦡� �⪫�祭�, ��� �㦡�, ����� � ������� �� ���, �� ����� ���� ����饭�.</SVCDESC>
				<SVCSTARTMODE>Auto</SVCSTARTMODE>
				<SVCPATH>C:\WINDOWS\system32\svchost.exe -k LocalServiceNetworkRestricted</SVCPATH>
				<SVCSTARTNAME>NT Authority\LocalService</SVCSTARTNAME>
				<SVCEXITCODE>0</SVCEXITCODE>
				<SVCSPECEXITCODE>0</SVCSPECEXITCODE>
			</SERVICE>

**Comment by gillesdubois** [comment]
Hi,

Latest releases comes with powershell and thus won't be impacted by this behavior anymore.

Regards,
Gilles Dubois.
